version: "3.9"
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app:cached
    ports:
      - "3000:3000"
    tty: true  

networks:
  postgres-network:
    driver: bridge
